# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube_mp3_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QIcon('bxl-youtube.ico'))
        MainWindow.setObjectName("Youtube to MP3")
        MainWindow.resize(358, 304)
        MainWindow.setMinimumSize(QtCore.QSize(358, 304))
        MainWindow.setMaximumSize(QtCore.QSize(358, 304))
        MainWindow.setStyleSheet("background-color:rgb(38, 38, 38)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QLabel{\n"
"color:white\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius: 4px;\n"
"color:rgb(205, 205, 205);\n"
"background-color:rgb(67, 67, 67);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius: 4px;\n"
"color:white;\n"
"background-color:rgb(82, 82, 82);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius: 4px;\n"
"background-color:rgb(83, 139, 203) ;\n"
"color: white \n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 171, 21))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 90, 71, 23))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 90, 161, 21))
        self.lineEdit.setStyleSheet("color:rgb(217, 217, 217)")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 120, 201, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 90, 71, 23))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 120, 111, 41))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 210, 321, 61))
        self.plainTextEdit.setStyleSheet("color: rgb(0, 255, 0)")
        self.plainTextEdit.setTabChangesFocus(False)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 171, 21))
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 30, 391, 16))
        self.frame.setStyleSheet("background-color:rgb(38, 38, 38);\n"
"border-color: rgb(117, 117, 117);\n"
"border-style: solid solid solid solid;\n"
"border-width: 0px 0px 1px 0px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 358, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.lineEdit.paste)
        self.pushButton_3.clicked.connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube to MP3"))
        self.label.setText(_translate("MainWindow", "Video or playlist URL:"))
        self.pushButton.setText(_translate("MainWindow", "Paste URL"))
        self.pushButton_2.setText(_translate("MainWindow", "Download"))
        self.pushButton_3.setText(_translate("MainWindow", "Clear"))
        self.pushButton_4.setText(_translate("MainWindow", "Set folder.."))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Set the save folder first..."))
        self.label_2.setText(_translate("MainWindow", "Status Console:"))
        self.label_3.setText(_translate("MainWindow", "Youtube to MP3"))
